### PR TITLE
Quoted & added protocol:// for all hyperlinks

### PR DESCRIPTION
**Pull request by eldang**
NB: I don’t know if this matters!  It was my attempt at fixing the issue whereby only some snuggets’ links get expanded.  If it turns out to be irrelevant, we can always delete this PR.

### CODE REVIEW

**Comment by nein09** [comment]
It's not a bad thought, but the real fix is in the PR I just opened.

**Comment by eldang** [comment]
Empirically: the quoting doesn't matter (but also does no harm), but the protocol:// does because without it we get things like:

http://23.92.25.126/www.smart911.com

**Comment by nein09** [comment]
Aha! Good catch.

**Comment by eldang** [comment]
(but you're right that #50 was the actual fix for the link expansion issue)

**Pull request merged**
