### PR TITLE
Reworked area boundary so it can be styled

### PR DESCRIPTION
**Pull request by eldang**

### CODE REVIEW

**Comment by nein09** [comment]
Looking good! I'll wait for Carson to reply- if she says 'orange', I'll merge.

**Comment by nein09** [comment]
orange I glad to have this in?

**Comment by eldang** [comment]
Actually, hold off a minute anyway.  I’m close to getting the mouse pointers sorted out.

Eldan Goldenberg
eldang@gmail.com | @eldang | eldan.co.uk | skype: eldang
PGP public key: http://eldan.co.uk/eldang.asc

**Comment by nein09** [comment]
whoops.

**Comment by nein09** [comment]
:large_orange_diamond:

**Comment by eldang** [comment]
nbd.  It’ll get rolled into the next PR.

**Pull request merged**
